/**
 * Portfolio Summary export utilities: HTML and PDF (print-window).
 * Ported from FSI App — podcast export removed.
 */

interface HtmlExportOptions {
    title: string;
    subtitle?: string;
    summaryMarkdown: string;
    generatedAt?: string | null;
    filenamePrefix?: string;
    entityCount?: number;
    entityLabel?: string;
    readTime?: string;
    model?: string;
}

export function useSummaryExport() {
    function exportSummaryAsHtml(opts: HtmlExportOptions): void {
        const now = opts.generatedAt ? new Date(opts.generatedAt) : new Date();
        const yy = String(now.getFullYear()).slice(-2);
        const mm = String(now.getMonth() + 1).padStart(2, '0');
        const dd = String(now.getDate()).padStart(2, '0');
        const fileDate = `${yy}${mm}${dd}`;
        const prefix = opts.filenamePrefix || 'summary';
        const filename = `${prefix}-${fileDate}.html`;

        // Convert markdown to basic HTML (naive, just paragraphs + headings)
        const body = opts.summaryMarkdown
            .replace(/^### (.+)$/gm, '<h3>$1</h3>')
            .replace(/^## (.+)$/gm, '<h2>$1</h2>')
            .replace(/^# (.+)$/gm, '<h1>$1</h1>')
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            .replace(/^- (.+)$/gm, '<li>$1</li>')
            .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
            .replace(/\n\n/g, '</p><p>')
            .replace(/^(?!<[a-z])(.+)$/gm, '<p>$1</p>');

        const meta = [
            opts.entityCount != null
                ? `${opts.entityCount} ${opts.entityLabel || 'entities'}`
                : null,
            opts.readTime ?? null,
            opts.model ?? null,
        ]
            .filter(Boolean)
            .join(' · ');

        const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(opts.title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 11pt; line-height: 1.65; color: #2c3e50; max-width: 800px; margin: 0 auto; padding: 2rem; }
    .header { border-bottom: 2px solid #333; padding-bottom: 1rem; margin-bottom: 1.5rem; }
    .header-label { font-size: 10pt; color: #666; text-transform: uppercase; letter-spacing: .1em; margin-bottom: .25rem; }
    .header-title { font-size: 18pt; font-weight: bold; }
    .header-meta { font-size: 10pt; color: #666; margin-top: .5rem; }
    h1 { font-size: 14pt; font-weight: 600; margin-top: 1.5rem; margin-bottom: .75rem; padding-bottom: .4rem; border-bottom: 2px solid #10b981; }
    h2 { font-size: 12pt; font-weight: 600; margin-top: 1.25rem; margin-bottom: .5rem; }
    h3 { font-size: 11pt; font-weight: 600; margin-top: 1rem; margin-bottom: .4rem; }
    p { margin-bottom: .75rem; }
    ul { margin-bottom: 1rem; padding-left: 1.5rem; }
    li { margin-bottom: .5rem; }
    strong { font-weight: 600; color: #1a202c; }
    em { font-style: italic; color: #718096; font-size: .9em; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 9pt; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <div class="header">
    <div class="header-label">${escapeHtml(opts.subtitle || 'Portfolio Risk Briefing')}</div>
    <div class="header-title">${escapeHtml(opts.title)}</div>
    ${meta ? `<div class="header-meta">${escapeHtml(meta)}</div>` : ''}
  </div>
  ${body}
  <div class="footer">Generated by Prism · ${now.toLocaleString()}</div>
</body>
</html>`;

        const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    }

    return { exportSummaryAsHtml };
}

function escapeHtml(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}
